### PR TITLE
Fix mine.c for Python 3.7 C API, update travis.yml configuration file

### PR DESCRIPTION
**Pull request by sdpython**

### CODE REVIEW

**Comment by clegaspi** [comment]
Hi there,

Do you know if there are any plans to merge this PR? I would like to be able to use Python 3.7.2 with minepy in my project.

Thanks!

--Christian

**Comment by davidealbanese** [comment]
Fixed in version 1.2.3.

**Comment by clegaspi** [comment]
Thank you! Much appreciated. I've been installing minepy using `conda install -c bioconda minepy`. Could I please request that the anaconda repository be updated to the latest version? 

Thank you!

**Comment by davidealbanese** [comment]
Sure!

Davide

**Comment by clegaspi** [comment]
Great, thank you, Davide!

--Christian

**Pull request closed without merging**
